%% ===================================================================
% run_apvss_baseline.m
% Baseline APV-SS simulation driver (Yuma climate) with crop toggle.
%
% Stages:
%   1. Loads pre-computed hourly radiative outputs for the selected config
%      (groundIrradiance/, panelIrradiance/, PVPerformance/, viewfactor_groundPV/).
%      These hourly .mat files are generated by Main_load_files{1..4}.m in
%      src/ (see Stage 0 in README).
%   2. Aggregates hourly outputs to daily totals.
%   3. Couples crop + thermal + PV via simulateCoupledCropThermal4 using
%      either a lettuce or tomato crop struct.
%   4. Writes a single baseline .mat with growth, thermal and PV results.
%
% Configurable items: CROP, CONFIG_NAME, BASE_PATH, PLOTS_BASE_PATH.
% ===================================================================

clear; close all; clc;
total_tic = tic;

addpath(genpath(fullfile(pwd, 'src')));

%% === USER CONFIG ===================================================
CROP             = 'lettuce';                       % 'lettuce' | 'tomato'
CONFIG_NAME      = 'original';                      % hourly-data subfolder
BASE_PATH        = 'C:\APV_Claude\Yuma\APVSS';      % parent of CONFIG_NAME
PLOTS_BASE_PATH  = fullfile(BASE_PATH,'baseline_crop','plots_base.mat');

OUTPUT_DIR       = fullfile(pwd, 'output');
if ~exist(OUTPUT_DIR,'dir'); mkdir(OUTPUT_DIR); end

%% === LOAD SHARED PARAMETERS ========================================
fprintf('Loading shared parameters from %s...\n', PLOTS_BASE_PATH);
load(PLOTS_BASE_PATH, ...
    'IH','groundX','groundY','numGroundY','numGroundX','wavelengthDir', ...
    'Tao','wind_vel','rhao','DNI','DHI', ...
    'panelWidth','panelHeight','groundXmin','groundXmax', ...
    'groundYmin','groundYmax','sunrise','sunset','daylength', ...
    'cf_matrix','dirHorznIrradNormHourlyMod','difHorznIrradNormHourlyMod', ...
    'tspan','gamma','lambda','C_pv_front','C_pv_back', ...
    'C_ground_top','k_ground','C_crop','k_crop', ...
    'C_ground_inner','h_conv_inner','Pr', ...
    'ri','sp','target_head_weight', ...
    'planting_density','dry_matter_fraction','usable_fraction', ...
    'max_days','theta_m','Ca','Csl','Oa','ra','rb','Pre', ...
    'CT','T0','Vcmax0','g1','g0','rjv','theta','alpha', ...
    'Ws_init','Wg_init','GDD_init','c_shoot','c_root', ...
    'f_root','cp','c_gr_max','Tbase','c_lar', ...
    'ground_albedo','A_PV','numPanels');

Y = numGroundY;
X = numGroundX;
sig = 5.67e-8;
epsilon_pv = 0.85;
k_ext_new = 0.7;
hours_per_day = 24;
secondsPerHour = 3600;

%% === TIME WINDOW (Sept 1 -> Jan 31) ================================
startDate   = datetime(2022,9,1);
endDate     = datetime(2023,1,31);
nHoursYear  = numel(IH);

startDOY    = day(startDate,'dayofyear');     % 244
endDOY_next = day(endDate,'dayofyear');       % 31
startHour   = (startDOY-1)*hours_per_day + 1;
endHour     = endDOY_next * hours_per_day;
window_hours = [startHour:nHoursYear, 1:(endDOY_next*hours_per_day)];
window_days  = [startDOY:365, 1:endDOY_next];

sunrise   = sunrise(window_days);
sunset    = sunset(window_days);
daylength = daylength(window_days);
sun_hours = window_hours(IH(window_hours) > 0);

cf_matrix_window = cf_matrix(window_hours);

fprintf('Window: DOY %d -> DOY %d (%d sunlit hours)\n', ...
    startDOY, endDOY_next, numel(sun_hours));

%% === METEOROLOGY ====================================================
Tao_window  = Tao(window_hours);
wind_window = wind_vel(window_hours);
rhao_window = rhao(window_hours);

Tao_daily  = mean(reshape(Tao_window,24,[]).',2);
wind_daily = mean(reshape(wind_window,24,[]).',2);
rhao_daily = mean(reshape(rhao_window,24,[]).',2);
DNI_daily  = mean(reshape(DNI(window_hours),24,[]).',2);
DHI_daily  = mean(reshape(DHI(window_hours),24,[]).',2);

Twb = (Tao .* atan(0.151977*sqrt(rhao+8.313659))) + ...
      atan(Tao + rhao) - atan(rhao - 1.676331) + ...
      0.00391838*(rhao.^1.5).*atan(0.023101*rhao) - 4.686035;
eclear = 0.787 + 0.7641*log((Twb+273)/273);
esky   = (1 + 0.0224*cf_matrix - 0.0035*(cf_matrix.^2) + ...
         0.00028*(cf_matrix.^3)) .* eclear;
T_sky_K     = (Tao + 273.5) .* esky.^0.25;
T_sky_K_day = mean(reshape(T_sky_K(window_hours),24,[]).',2);

ground_albedo_int = trapz(wavelengthDir, ...
    ground_albedo.*dirHorznIrradNormHourlyMod(:,14)) / ...
    trapz(wavelengthDir, dirHorznIrradNormHourlyMod(:,14));

%% === CROP STRUCT TOGGLE ============================================
% Lettuce struct
cropStructLettuce      = struct();
cropStructLettuce.type = 'lettuce';

% Tomato struct
tomParams = struct();
tomParams.betaT   = 0.085;      tomParams.betaC   = 0.00085;
tomParams.FPN     = 0.5;        tomParams.FRPET   = 0.25;
tomParams.FRSTM   = 0.33;
tomParams.nodeNumber = [0 1.7 4.3 5.9 8 10 12 15 20 100];
tomParams.fN         = [0.15 0.15 0.16 0.16 0.18 0.18 0.19 0.20 0.20 0.20];
tomParams.LAI_init = 0.034;     tomParams.LAImax  = 5;
tomParams.NFF      = 8;         tomParams.nL      = 10;
tomParams.Nm       = 0.30;      tomParams.PD      = 3;
tomParams.PEEC     = 0.5;       tomParams.LFmax   = 2.52;
tomParams.POL_a = 0.18;  tomParams.POL_b = 0.15;  tomParams.POL_c = 13.6;
tomParams.POF_a = 24.5;  tomParams.POF_b = 0.08;  tomParams.POF_c = 15;
tomParams.Qe    = 0.06*30*1e-6*3600;
tomParams.RDfmax = 0.033;       tomParams.RDLmax  = 0.013;
tomParams.E      = 0.7;
tomParams.SLAmin = 0.015;       tomParams.SLAmax  = 0.025;
tomParams.K      = 0.7;         tomParams.m       = 0.1;
tomParams.Q10    = 1.7;         tomParams.RL      = 0.015;
tomParams.RF     = 0.008;
tomParams.Smax      = 100;
tomParams.eta_store = 1;        tomParams.eta_withd = 1;
tomParams.Tcrit  = 28;          tomParams.TPL     = 0.33;
tomParams.Tref   = 20;
tomParams.CO2       = 400;
tomParams.sunrise   = sunrise;
tomParams.sunset    = sunset;
tomParams.Thours    = Tao(window_hours);
tomParams.WF_target = 1200;

nL = tomParams.nL;
tomParams.Wprev_init   = zeros(Y,X);
tomParams.WFprev_init  = zeros(Y,X);
tomParams.LAIprev_init = tomParams.LAI_init * ones(Y,X);
tomParams.Nprev_init   = zeros(Y,X);
tomParams.Ns_init      = zeros(Y,X,nL);
tomParams.Nl_init      = zeros(Y,X,nL);
tomParams.Nf_init      = zeros(Y,X,nL);
tomParams.Rc_prev_init = zeros(Y,X);

SLAmin_new = tomParams.SLAmin;
SLAmax_new = tomParams.SLAmax;
betaT_new  = tomParams.betaT;
betaC_new  = tomParams.betaC;
SLAexp_new = 0.471;

cropTom        = struct();
cropTom.type   = 'tomato';
cropTom.params = tomParams;

switch lower(CROP)
    case 'lettuce', activeCrop = cropStructLettuce;
    case 'tomato',  activeCrop = cropTom;
    otherwise,      error('CROP must be ''lettuce'' or ''tomato''. Got: %s', CROP);
end

fprintf('Active crop: %s\n\n', activeCrop.type);

%% === LOAD HOURLY RADIATIVE OUTPUTS ==================================
directory_Yuma_APVSS = fullfile(BASE_PATH, CONFIG_NAME);

[groundIrradiance_Yuma_APVSS, hourNumbersSorted_Yuma_APVSS_grIr] = ...
    loadMatFilesFromDir_range( ...
        fullfile(directory_Yuma_APVSS, 'groundIrradiance'), ...
        'irradianceGround_hour_*.mat', ...
        'irradianceground_hour_(\d+)\.mat', ...
        startHour, endHour);

[panelirradiance_Yuma_APVSS, hourNumbersSorted_Yuma_APVSS_pair] = ...
    loadMatFilesFromDir_range( ...
        fullfile(directory_Yuma_APVSS, 'panelIrradiance'), ...
        'panelirradiance_hour_*.mat', ...
        'panelirradiance_hour_(\d+)\.mat', ...
        startHour, endHour);

[PV_Yuma_APVSS, hourNumbersSorted_Yuma_APVSS_PV] = ...
    loadMatFilesFromDir_range( ...
        fullfile(directory_Yuma_APVSS, 'PVPerformance'), ...
        'PVPanelPerformance_hour_*.mat', ...
        'pvpanelperformance_hour_(\d+)\.mat', ...
        startHour, endHour);

[VF_Yuma_APVSS, hourNumbersSorted_VF] = ...
    loadMatFilesFromDir_range( ...
        fullfile(directory_Yuma_APVSS, 'viewfactor_groundPV'), ...
        'viewFactor_hour_*.mat', ...
        'viewfactor_hour_(\d+)\.mat', ...
        startHour, endHour);

% Year-boundary reorder for hour vectors
if startHour > endHour
    for vname = {'grIr','pair','PV','VF'}
        switch vname{1}
            case 'grIr', src = 'hourNumbersSorted_Yuma_APVSS_grIr'; bag = 'groundIrradiance_Yuma_APVSS';
            case 'pair', src = 'hourNumbersSorted_Yuma_APVSS_pair'; bag = 'panelirradiance_Yuma_APVSS';
            case 'PV',   src = 'hourNumbersSorted_Yuma_APVSS_PV';   bag = 'PV_Yuma_APVSS';
            case 'VF',   src = 'hourNumbersSorted_VF';              bag = 'VF_Yuma_APVSS';
        end
        hrs = eval([src '(:);']);
        wrapMask = hrs < startHour;
        reorderIdx = [find(~wrapMask); find(wrapMask)];
        assignin('base', src, hrs(reorderIdx));
        S = eval(bag);
        flds = fieldnames(S);
        for f = 1:length(flds)
            S.(flds{f}) = S.(flds{f})(reorderIdx);
        end
        assignin('base', bag, S);
    end
end

hourNumbersSorted_Yuma_APVSS_grIr = hourNumbersSorted_Yuma_APVSS_grIr(:);
hourNumbersSorted_Yuma_APVSS_pair = hourNumbersSorted_Yuma_APVSS_pair(:);
hourNumbersSorted_Yuma_APVSS_PV   = hourNumbersSorted_Yuma_APVSS_PV(:);
hourNumbersSorted_VF              = hourNumbersSorted_VF(:);

nHours      = length(hourNumbersSorted_Yuma_APVSS_grIr);
day_of_year = ceil(hourNumbersSorted_Yuma_APVSS_grIr / 24);
[uniqueDays, ~, day_indices] = unique(day_of_year, 'stable');
numDays = numel(uniqueDays);
fprintf('Loaded %d calendar days (DOY %d -> %d)\n', ...
    numDays, uniqueDays(1), uniqueDays(end));

%% === DAILY AGGREGATION =============================================
daily_ePAR_totals      = cell(numDays,1);
daily_totals           = cell(numDays,1);
daily_ePAR_mole_totals = cell(numDays,1);

for d = 1:numDays
    hour_list = find(day_indices == d);
    sum_ePAR  = zeros(numGroundY, numGroundX);
    sum_total = zeros(numGroundY, numGroundX);
    sum_mole  = zeros(numGroundY, numGroundX);
    for h = hour_list'
        ePARh = groundIrradiance_Yuma_APVSS.ePAR_inten{h};
        PARh  = groundIrradiance_Yuma_APVSS.PAR_inten{h};
        IRh   = groundIrradiance_Yuma_APVSS.IR_inten{h};
        eMolh = groundIrradiance_Yuma_APVSS.ePAR_inten_mmole{h};
        if isempty(ePARh), continue; end
        sum_ePAR  = sum_ePAR  + (ePARh * secondsPerHour / 1e6);
        sum_total = sum_total + ((PARh + IRh) * secondsPerHour / 1e6);
        sum_mole  = sum_mole  + (eMolh * secondsPerHour / 1e6);
    end
    daily_ePAR_totals{d}      = sum_ePAR;
    daily_totals{d}           = sum_total;
    daily_ePAR_mole_totals{d} = sum_mole;
end

daily_front_totals     = zeros(numDays, numPanels);
daily_rear_totals      = zeros(numDays, numPanels);
daily_front_abs_totals = zeros(numDays, numPanels);
daily_rear_abs_totals  = zeros(numDays, numPanels);

for h = 1:nHours
    d = day_indices(h);
    fv = panelirradiance_Yuma_APVSS.Front_Irradiance_inten{h};
    rv = panelirradiance_Yuma_APVSS.Rear_Irradiance_inten{h};
    if ~isempty(fv)
        daily_front_totals(d,:) = daily_front_totals(d,:) + (fv' * secondsPerHour / 1e6);
        daily_rear_totals(d,:)  = daily_rear_totals(d,:)  + (rv' * secondsPerHour / 1e6);
    end
    front_specs = PV_Yuma_APVSS.Front_Irradiance_abs{h};
    rear_specs  = PV_Yuma_APVSS.Rear_Irradiance_abs{h};
    if isempty(front_specs), continue; end
    for p = 1:numPanels
        fa = front_specs{p}; ra = rear_specs{p};
        if isempty(fa), continue; end
        daily_front_abs_totals(d,p) = daily_front_abs_totals(d,p) + ...
            trapz(wavelengthDir, fa) * secondsPerHour / 1e6;
        daily_rear_abs_totals(d,p)  = daily_rear_abs_totals(d,p)  + ...
            trapz(wavelengthDir, ra) * secondsPerHour / 1e6;
    end
end

%% === GROUND <-> PV VIEW FACTOR CONVERSION ==========================
nHoursVF = length(hourNumbersSorted_VF);
viewFactor_GroundToPVFront = cell(nHoursVF,1);
viewFactor_GroundToPVRear  = cell(nHoursVF,1);

for h = 1:nHoursVF
    panelF = VF_Yuma_APVSS.viewFactor_FrontPVGround_sparse{h};
    panelR = VF_Yuma_APVSS.viewFactor_RearPVGround_sparse{h};
    if isempty(panelF)
        viewFactor_GroundToPVFront{h} = [];
        viewFactor_GroundToPVRear{h}  = [];
        continue
    end
    [VF_F, ~] = convertPVToGroundToGroundToPV(panelF, panelWidth, panelHeight, ...
        groundXmin, groundXmax, groundYmin, groundYmax, numGroundX, numGroundY);
    [VF_R, ~] = convertPVToGroundToGroundToPV(panelR, panelWidth, panelHeight, ...
        groundXmin, groundXmax, groundYmin, groundYmax, numGroundX, numGroundY);
    viewFactor_GroundToPVFront{h} = VF_F;
    viewFactor_GroundToPVRear{h}  = VF_R;
end

%% === COUPLED CROP + THERMAL SIMULATION =============================
fprintf('Running crop+thermal simulation (%s)...\n', activeCrop.type);
[growth_results, month_data] = simulateCoupledCropThermal4( ...
    tspan, numGroundX, numGroundY, Tao_daily, ...
    rhao_daily, wind_daily, gamma, lambda, ...
    C_pv_front, C_pv_back, ...
    daily_front_abs_totals, daily_rear_abs_totals, ...
    C_ground_top, k_ground, ground_albedo_int, C_crop, ...
    k_crop, C_ground_inner, h_conv_inner, ...
    wavelengthDir, panelWidth, panelHeight, Pr, ...
    numPanels, sig, epsilon_pv, ...
    ri, sp, daily_ePAR_totals, target_head_weight, ...
    planting_density, dry_matter_fraction, usable_fraction, ...
    max_days, theta_m, Ca, Csl, Oa, ra, rb, Pre, ...
    CT, T0, Vcmax0, g1, g0, rjv, theta, alpha, ...
    Ws_init, Wg_init, GDD_init, c_shoot, c_root, ...
    f_root, cp, c_gr_max, Tbase, c_lar, ...
    T_sky_K_day, hours_per_day, hourNumbersSorted_VF, ...
    viewFactor_GroundToPVFront, viewFactor_GroundToPVRear, ...
    cf_matrix_window, activeCrop, ...
    daily_totals, daily_ePAR_mole_totals, k_ext_new, ...
    SLAmin_new, SLAmax_new, SLAexp_new, betaT_new, betaC_new);

%% === PV ENERGY ROLLUP ===============================================
nHours_PV = length(hourNumbersSorted_Yuma_APVSS_PV);
hourly_Pmp = zeros(nHours_PV, numPanels);
for h = 1:nHours_PV
    pr = PV_Yuma_APVSS.panelResults{h};
    if isempty(pr), continue; end
    for p = 1:numPanels
        hourly_Pmp(h,p) = pr(p).DiodeResult.Pmp;
    end
end
hourly_system_power = sum(hourly_Pmp, 2);

daily_energy_panel  = zeros(numDays, numPanels);
daily_energy_system = zeros(numDays, 1);
for h = 1:nHours_PV
    d = day_indices(h);
    daily_energy_panel(d,:) = daily_energy_panel(d,:) + hourly_Pmp(h,:);
    daily_energy_system(d)  = daily_energy_system(d)  + hourly_system_power(h);
end
E_APVSS_kWh = sum(daily_energy_system) / 1000;
fprintf('Season PV energy: %.2f kWh\n', E_APVSS_kWh);

%% === SAVE ===========================================================
save_file = fullfile(OUTPUT_DIR, ...
    sprintf('baseline_%s_%s.mat', CONFIG_NAME, activeCrop.type));
save(save_file, ...
    'CROP','CONFIG_NAME', ...
    'window_hours','window_days','uniqueDays','day_indices','numDays', ...
    'sunrise','sunset','daylength', ...
    'daily_ePAR_totals','daily_totals','daily_ePAR_mole_totals', ...
    'daily_front_totals','daily_rear_totals', ...
    'daily_front_abs_totals','daily_rear_abs_totals', ...
    'Tao_daily','wind_daily','rhao_daily','DNI_daily','DHI_daily', ...
    'T_sky_K_day','ground_albedo_int', ...
    'viewFactor_GroundToPVFront','viewFactor_GroundToPVRear', ...
    'growth_results','month_data', ...
    'hourly_Pmp','hourly_system_power', ...
    'daily_energy_panel','daily_energy_system','E_APVSS_kWh', ...
    '-v7.3');
fprintf('Saved %s\n', save_file);

fprintf('Total runtime: %.1f min\n', toc(total_tic)/60);
