function result = call_prosail(LAI, skyl, zen, azim)
    % Create a struct with values to pass
    vars = struct( ...
        'LAI', LAI, ...
        'skyl', skyl, ...
        'zen', zen, ...
        'azim', azim ...
    );

    % Inline Python script that assigns variables and runs the function
    code = [
        "lai = " + string(LAI) + newline + ...
        "skyl = " + string(skyl) + newline + ...
        "zen = " + string(zen) + newline + ...
        "azim = " + string(azim) + newline + ...
        "result = run_prosail_single(lai, skyl, zen, azim)"
    ];

    result = pyrun(code, "result");
end