function S = loadSkyDiffuseReduction(filename)
    % loadSkyDiffuseReduction - Load sky diffuse reduction data into a struct.
    % Safe for use in parfor loops.

    arguments
        filename (1,:) char
    end

    S = load(filename, ...
        'avg_blocked_dualHM1', ...
        'reduction_dualHM1', ...
        'avg_blocked_dualHM2', ...
        'reduction_dualHM2', ...
        'avg_blocked_dual', ...
        'reduction_dual', ...
        'SVF_ground');
end