function [sun_tables, shade_tables] = run_prosail_batch(unique_LAI, zenith1, az_s_matrix1)
    mainFolder = "C:\Users\eravishankar\OneDrive - Cal Poly Pomona\NCSU_Agrivoltaics_Paper_AppliedEnergy_2025\Mat_Files\Yuma_APVSS\HPC_02222026\part1\";
    python_script_path = strrep(fullfile(mainFolder, 'pypro4sail'), '\', '/');
    pyrun("import sys")
    pyrun("sys.path.append('" + python_script_path + "')")
    pyrun("from prosail_run import run_prosail_single")% Build angle bins only for simulated hours

    % Initialize result struct
    result = struct;

    for i = 1:length(unique_LAI)
        LAI_val = unique_LAI(i,1);

        % Use the same zenith and azimuth for all entries
        sun_struct = call_prosail(LAI_val, 0.1, zenith1, az_s_matrix1);
        shade_struct = call_prosail(LAI_val, 0.9, zenith1, az_s_matrix1);

        result(i).LAI = LAI_val;
        result(i).sun = sun_struct;
        result(i).shade = shade_struct;
    end

    % Preallocate cell arrays for storing tables
    sun_tables = cell(length(result), 1);
    shade_tables = cell(length(result), 1);

    for i = 1:length(result)
        sun = result(i).sun;
        shade = result(i).shade;

        sun_tables{i} = table( ...
            double(py.array.array('d', py.numpy.nditer(sun{'Wavelength_nm'})))', ...
            double(py.array.array('d', py.numpy.nditer(sun{'Canopy_Reflectance'})))', ...
            double(py.array.array('d', py.numpy.nditer(sun{'Canopy_Transmittance'})))', ...
            double(py.array.array('d', py.numpy.nditer(sun{'Canopy_Absorptance'})))', ...
            double(py.array.array('d', py.numpy.nditer(sun{'Leaf_Reflectance'})))', ...
            double(py.array.array('d', py.numpy.nditer(sun{'Leaf_Transmittance'})))', ...
            double(py.array.array('d', py.numpy.nditer(sun{'Leaf_Absorptance'})))', ...
            'VariableNames', {'Wavelength_nm', 'CanopyReflectance', 'CanopyTransmittance', ...
            'CanopyAbsorptance', 'LeafReflectance', 'LeafTransmittance', 'LeafAbsorptance'});

        shade_tables{i} = table( ...
            double(py.array.array('d', py.numpy.nditer(shade{'Wavelength_nm'})))', ...
            double(py.array.array('d', py.numpy.nditer(shade{'Canopy_Reflectance'})))', ...
            double(py.array.array('d', py.numpy.nditer(shade{'Canopy_Transmittance'})))', ...
            double(py.array.array('d', py.numpy.nditer(shade{'Canopy_Absorptance'})))', ...
            double(py.array.array('d', py.numpy.nditer(shade{'Leaf_Reflectance'})))', ...
            double(py.array.array('d', py.numpy.nditer(shade{'Leaf_Transmittance'})))', ...
            double(py.array.array('d', py.numpy.nditer(shade{'Leaf_Absorptance'})))', ...
            'VariableNames', {'Wavelength_nm', 'CanopyReflectance', 'CanopyTransmittance', ...
            'CanopyAbsorptance', 'LeafReflectance', 'LeafTransmittance', 'LeafAbsorptance'});
    end
end
