function run_uncertainty_lettuce( ...
    N, ...
    tspan, numGroundX, numGroundY, ...
    Tao_daily, rhao_daily, wind_daily, ...
    gamma_var, lambda, ...
    C_pv_front, C_pv_back, ...
    daily_front_abs_totals, daily_rear_abs_totals, ...
    C_ground_top, k_ground, ground_albedo_int, C_crop, ...
    k_crop, C_ground_inner, h_conv_inner, ...
    wavelengthDir, panelWidth, panelHeight, Pr, ...
    numPanels, sig, epsilon_pv, ...
    ri, sp, daily_ePAR_totals, ...
    target_head_weight, planting_density, ...
    dry_matter_fraction, usable_fraction, ...
    max_days, theta_m, ...
    Ca, Csl, Oa, ra, rb, Pre, ...
    CT, T0, ...
    Vcmax0, g1, g0, rjv, theta, alpha, ...
    Ws_init, Wg_init, GDD_init, ...
    c_shoot, c_root, f_root, cp, ...
    c_gr_max, Tbase, c_lar, ...
    T_sky_K_day, ...
    hours_per_day, hourNumbersSorted_VF, ...
    viewFactor_GroundToPVFront, ...
    viewFactor_GroundToPVRear, ...
    cf_matrix, cropStructLettuce, ...
    daily_totals, daily_ePAR_mole_totals,k_ext,...
    SLAmin,SLAmax,...
        SLAexp,betaT,betaC)

fprintf('\nRunning uncertainty N = %d\n', N)

rng(1,'combRecursive')

scale_Vcmax  = 1 + 0.10*(2*rand(N,1)-1);
scale_alpha  = 1 + 0.10*(2*rand(N,1)-1);
scale_g1     = 1 + 0.10*(2*rand(N,1)-1);
scale_rjv    = 1 + 0.10*(2*rand(N,1)-1);   % NEW
scale_thetaF = 1 + 0.05*(2*rand(N,1)-1);   % curvature parameter

% ===========================
% THERMAL (±20%)
% ===========================
scale_conv   = 1 + 0.20*(2*rand(N,1)-1);

% ===========================
% STRUCTURAL (±10%)
% ===========================
scale_c_lar  = 1 + 0.10*(2*rand(N,1)-1);
scale_c_gr   = 1 + 0.10*(2*rand(N,1)-1);
scale_theta  = 1 + 0.05*(2*rand(N,1)-1);
scale_DMF    = 1 + 0.05*(2*rand(N,1)-1);
scale_SLAmin = 1 + 0.10*(2*rand(N,1)-1);
scale_SLAmax = 1 + 0.10*(2*rand(N,1)-1);
scale_SLAexp = 1 + 0.10*(2*rand(N,1)-1);
% ===========================
% CANOPY OPTICS (±10%)
% ===========================
scale_kext   = 1 + 0.10*(2*rand(N,1)-1);   % NEW (Beer extinction)

% ===========================
% RADIATIVE INPUT (±5%)
% ===========================
scale_rad    = 1 + 0.05*(2*rand(N,1)-1);   % NEW (Perez/SMARTS envelope)

% Run first iteration outside parfor to define structure
Vcmax0_new = Vcmax0 * scale_Vcmax(1);
alpha_new  = alpha  * scale_alpha(1);
g1_new     = g1     * scale_g1(1);
rjv_new    = rjv    * scale_rjv(1);
thetaF_new = theta  * scale_thetaF(1);
scale_betaT = 1 + 0.10*(2*rand(N,1)-1);
scale_betaC = 1 + 0.10*(2*rand(N,1)-1);
h_conv_new = h_conv_inner * scale_conv(1);

c_lar_new   = c_lar * scale_c_lar(1);
c_gr_max_new= c_gr_max * scale_c_gr(1);
theta_m_new = theta_m * scale_theta(1);
dry_matter_fraction_new = dry_matter_fraction * scale_DMF(1);
SLAmin_new = SLAmin * scale_SLAmin(1);
SLAmax_new = SLAmax * scale_SLAmax(1);
SLAexp_new = SLAexp * scale_SLAexp(1);
betaT_new = betaT * scale_betaT(1);
betaC_new = betaC * scale_betaC(1);
k_ext_new = k_ext * scale_kext(1);   % <-- after you convert 0.7 to k_ext

% Radiative envelope
daily_ePAR_totals_new = daily_ePAR_totals .* scale_rad(1);
daily_totals_new =  daily_totals.*scale_rad(1);
daily_ePAR_mole_totals_new = aily_ePAR_mole_totals.*scale_rad(1);
daily_front_abs_totals_new = daily_front_abs_totals .* scale_rad(1);
daily_rear_abs_totals_new  = daily_rear_abs_totals  .* scale_rad(1);

[~, month_data] = simulateCoupledCropThermal4( ...
    tspan, numGroundX, numGroundY, ...
    Tao_daily, rhao_daily, wind_daily, ...
    gamma_var, lambda, ...
    C_pv_front, C_pv_back, ...
    daily_front_abs_totals_new, daily_rear_abs_totals_new, ...
    C_ground_top, k_ground, ground_albedo_int, C_crop, ...
    k_crop, C_ground_inner, h_conv_new, ...
    wavelengthDir, panelWidth, panelHeight, Pr, ...
    numPanels, sig, epsilon_pv, ...
    ri, sp, daily_ePAR_totals_new, ...
    target_head_weight, planting_density, ...
    dry_matter_fraction_new, usable_fraction, ...
    max_days, theta_m_new, ...
    Ca, Csl, Oa, ra, rb, Pre, ...
    CT, T0, Vcmax0_new, g1_new, g0, rjv_new, thetaF_new, alpha_new, ...
    Ws_init, Wg_init, GDD_init, ...
    c_shoot, c_root, f_root, cp, ...
    c_gr_max_new, Tbase, c_lar_new, ...
    T_sky_K_day, hours_per_day, ...
    hourNumbersSorted_VF, ...
    viewFactor_GroundToPVFront, ...
    viewFactor_GroundToPVRear, ...
    cf_matrix, cropStructLettuce, ...
    daily_totals_new, daily_ePAR_mole_totals_new,k_ext_new,...
    SLAmin_new,SLAmax_new,...
        SLAexp_new,betaT_new,betaC_new);

template = extract_summary(month_data);

results = repmat(struct('summary', [], 'month_data', []), N, 1);
results(1).summary = template;
results(1).month_data = extract_light_month_data(month_data);



parfor i = 2:N
    Vcmax0_new = Vcmax0 * scale_Vcmax(i);
    alpha_new  = alpha  * scale_alpha(i);
    g1_new     = g1     * scale_g1(i);
    rjv_new    = rjv    * scale_rjv(i);
    thetaF_new = theta  * scale_thetaF(i);
    
    h_conv_new = h_conv_inner * scale_conv(i);
    
    c_lar_new   = c_lar * scale_c_lar(i);
    c_gr_max_new= c_gr_max * scale_c_gr(i);
    theta_m_new = theta_m * scale_theta(i);
    dry_matter_fraction_new = dry_matter_fraction * scale_DMF(i);
    
    k_ext_new = k_ext * scale_kext(i);   % <-- after you convert 0.7 to k_ext
    
    % Radiative envelope
    daily_ePAR_totals_new = daily_ePAR_totals .* scale_rad(i);
    daily_totals_new =  daily_totals.*scale_rad(i);
    daily_ePAR_mole_totals_new = aily_ePAR_mole_totals.*scale_rad(i);
    daily_front_abs_totals_new = daily_front_abs_totals .* scale_rad(i);
    daily_rear_abs_totals_new  = daily_rear_abs_totals  .* scale_rad(i);

    SLAmin_new = SLAmin * scale_SLAmin(i);
    SLAmax_new = SLAmax * scale_SLAmax(i);
    SLAexp_new = SLAexp * scale_SLAexp(i);
    betaT_new = betaT * scale_betaT(i);
    betaC_new = betaC * scale_betaC(i);

   
    [~, month_data] = simulateCoupledCropThermal4( ...
        tspan, numGroundX, numGroundY, ...
        Tao_daily, rhao_daily, wind_daily, ...
        gamma_var, lambda, ...
        C_pv_front, C_pv_back, ...
        daily_front_abs_totals_new, daily_rear_abs_totals_new, ...
        C_ground_top, k_ground, ground_albedo_int, C_crop, ...
        k_crop, C_ground_inner, h_conv_new, ...
        wavelengthDir, panelWidth, panelHeight, Pr, ...
        numPanels, sig, epsilon_pv, ...
        ri, sp, daily_ePAR_totals_new, ...
        target_head_weight, planting_density, ...
        dry_matter_fraction_new, usable_fraction, ...
        max_days, theta_m_new, ...
        Ca, Csl, Oa, ra, rb, Pre, ...
        CT, T0, Vcmax0_new, g1_new, g0, rjv_new, thetaF_new, alpha_new, ...
        Ws_init, Wg_init, GDD_init, ...
        c_shoot, c_root, f_root, cp, ...
        c_gr_max_new, Tbase, c_lar_new, ...
        T_sky_K_day, hours_per_day, ...
        hourNumbersSorted_VF, ...
        viewFactor_GroundToPVFront, ...
        viewFactor_GroundToPVRear, ...
        cf_matrix, cropStructLettuce, ...
        daily_totals_new, daily_ePAR_mole_totals_new,k_ext_new,SLAmin_new,SLAmax_new,...
        SLAexp_new,betaT_new,betaC_new);

        results(i).summary = extract_summary(month_data);
        results(i).month_data = extract_light_month_data(month_data);

end

if ~exist('runs','dir'); mkdir('runs'); end
save('runs/lettuce_uncertainty_results.mat','results','-v7.3')

fprintf('Done.\n')
end