function saveSpectralFactors_APVSS(filename, R_HM1, R_HM2, R_Panel,A_HM1,A_HM2,...
        A_Panel,T_HM1,T_HM2,T_Panel,...
        dirHorznIrradNormHourlyMod_new, difHorznIrradNormHourlyMod_new)
       
        % Save the variable in the specified subfolder
        save(filename, 'R_HM1', 'R_HM2', 'R_Panel','A_HM1','A_HM2',...
        'A_Panel','T_HM1','T_HM2','T_Panel',...
        'dirHorznIrradNormHourlyMod_new', 'difHorznIrradNormHourlyMod_new');
end