function saveGroundIrradiance_APVSS(filename,PAR_inten, ePAR_inten,...
            IR_inten,Ri_inten,PAR_inten_mmole, ePAR_inten_mmole,...
            shadingMaskhm1,...
            shadingMaskhm2)
       
        % Save the variable in the specified subfolder
        save(filename, 'PAR_inten', 'ePAR_inten',...
            'IR_inten','Ri_inten','PAR_inten_mmole', 'ePAR_inten_mmole',...
            'shadingMaskhm1',...
            'shadingMaskhm2');
end