function savePanelHMIrradiance(filename,Front_Irradiance_inten, ...
            Front_Irradiance_inten_HM1,Rear_Irradiance_inten_HM1, Rear_Irradiance_inten,...
            Front_Irradiance_inten_HM2,...
            Rear_Irradiance_inten_HM2,panel_reflected_front_inten, ...
            panel_reflected_front_inten_HM1, ...
            panel_reflected_rear_inten_HM1,...
            panel_reflected_rear_inten,...
            panel_reflected_front_inten_HM2, ...
            panel_reflected_rear_inten_HM2,...
            IB_Front_inten,...
            IB_HM1_Front_inten,IB_HM1_Back_inten,...
            I_Alb_Front_inten,I_Alb_HM1_Front,...
            I_Alb_HM1_Rear,ID_Iso_Front_inten,...
            ID_HM1_Iso_Front_inten, ID_HM1_Iso_Rear_inten,...
            ID_Cir_Front_inten,...
            ID_HM1_Cir_Front_inten, ID_HM1_Cir_Rear_inten,...
            ID_Hor_Front_inten,...
            ID_HM1_Hor_Front_inten, ID_HM1_Hor_Rear_inten,...
            IB_Back_inten,...
            IB_HM2_Front_inten,IB_HM2_Back_inten,...
            I_Alb_Rear_inten,I_Alb_HM2_Front,...
            I_Alb_HM2_Rear,ID_Iso_Rear_inten,...
            ID_HM2_Iso_Front_inten, ID_HM2_Iso_Rear_inten,...
            ID_Cir_Rear_inten, ...
            ID_HM2_Cir_Front_inten, ID_HM2_Cir_Rear_inten, ...
            ID_Hor_Rear_inten,...
            ID_HM2_Hor_Front_inten, ID_HM2_Hor_Rear_inten)
       
        % Save the variable in the specified subfolder
        save(filename, 'Front_Irradiance_inten', ...
            'Front_Irradiance_inten_HM1','Rear_Irradiance_inten_HM1', 'Rear_Irradiance_inten',...
            'Front_Irradiance_inten_HM2',...
            'Rear_Irradiance_inten_HM2','panel_reflected_front_inten', ...
            'panel_reflected_front_inten_HM1', ...
            'panel_reflected_rear_inten_HM1',...
            'panel_reflected_rear_inten',...
            'panel_reflected_front_inten_HM2', ...
            'panel_reflected_rear_inten_HM2',...
            'IB_Front_inten',...
            'IB_HM1_Front_inten','IB_HM1_Back_inten',...
            'I_Alb_Front_inten','I_Alb_HM1_Front',...
            'I_Alb_HM1_Rear','ID_Iso_Front_inten',...
            'ID_HM1_Iso_Front_inten', 'ID_HM1_Iso_Rear_inten',...
            'ID_Cir_Front_inten',...
            'ID_HM1_Cir_Front_inten', 'ID_HM1_Cir_Rear_inten',...
            'ID_Hor_Front_inten',...
            'ID_HM1_Hor_Front_inten', 'ID_HM1_Hor_Rear_inten',...
            'IB_Back_inten',...
            'IB_HM2_Front_inten','IB_HM2_Back_inten',...
            'I_Alb_Rear_inten','I_Alb_HM2_Front',...
            'I_Alb_HM2_Rear','ID_Iso_Rear_inten',...
            'ID_HM2_Iso_Front_inten', 'ID_HM2_Iso_Rear_inten',...
            'ID_Cir_Rear_inten', ...
            'ID_HM2_Cir_Front_inten', 'ID_HM2_Cir_Rear_inten', ...
            'ID_Hor_Rear_inten',...
            'ID_HM2_Hor_Front_inten', 'ID_HM2_Hor_Rear_inten');
end